package com.noteflowai.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material.icons.filled.Summarize
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import com.noteflowai.app.R
import com.noteflowai.app.data.digest.DailyDigest
import com.noteflowai.app.data.noteDisplayTitle
import com.noteflowai.app.viewmodel.MainViewModel
import java.text.SimpleDateFormat
import java.util.*

// Header date — SimpleDateFormat is not thread-safe, but composition is single-threaded.
private val DIGEST_DATE_FORMAT = SimpleDateFormat("MMMM d, yyyy", Locale.getDefault())

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun DailyDigestScreen(
    viewModel: MainViewModel,
    onBack: () -> Unit,
    onOpenNote: (String) -> Unit = {},
    modifier: Modifier = Modifier
) {
    val digest by viewModel.dailyDigest.collectAsStateWithLifecycle()
    val isRefreshing by viewModel.isDigestRefreshing.collectAsStateWithLifecycle()
    val digestError by viewModel.digestError.collectAsStateWithLifecycle()

    // Pick up digests generated by the 8:00 alarm while the app was alive.
    LaunchedEffect(Unit) { viewModel.loadDigestFromDisk() }

    com.noteflowai.app.ui.components.FreshScreen(
        title = stringResource(R.string.daily_digest_title),
        onBack = onBack,
        modifier = modifier,
        backContentDescription = stringResource(R.string.common_back),
        actions = {
            if (isRefreshing) {
                CircularProgressIndicator(
                    modifier = Modifier.size(24.dp),
                    strokeWidth = 2.dp
                )
            } else {
                IconButton(onClick = { viewModel.refreshDigest() }) {
                    Icon(Icons.Default.Refresh, contentDescription = stringResource(R.string.weekly_review_refresh))
                }
            }
        }
    ) { padding ->
        val currentDigest = digest
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(padding)
        ) {
            digestError?.let {
                Text(
                    text = it,
                    style = MaterialTheme.typography.bodySmall,
                    color = MaterialTheme.colorScheme.error,
                    modifier = Modifier.padding(horizontal = 16.dp, vertical = 8.dp)
                )
            }
            if (currentDigest == null) {
            Box(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth(),
                contentAlignment = Alignment.Center
            ) {
                Column(horizontalAlignment = Alignment.CenterHorizontally) {
                    Surface(
                        shape = androidx.compose.foundation.shape.CircleShape,
                        color = MaterialTheme.colorScheme.primaryContainer,
                        modifier = Modifier.size(64.dp)
                    ) {
                        Box(contentAlignment = Alignment.Center, modifier = Modifier.fillMaxSize()) {
                            Icon(
                                Icons.Default.Summarize,
                                contentDescription = null,
                                tint = MaterialTheme.colorScheme.onPrimaryContainer,
                                modifier = Modifier.size(32.dp)
                            )
                        }
                    }
                    Spacer(modifier = Modifier.height(16.dp))
                    Text(
                        stringResource(R.string.daily_digest_empty_title),
                        style = MaterialTheme.typography.titleMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                    Spacer(modifier = Modifier.height(8.dp))
                    Text(
                        stringResource(R.string.daily_digest_empty_subtitle),
                        style = MaterialTheme.typography.bodyMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }
            }
        } else {
            val d = currentDigest
            LazyColumn(
                modifier = Modifier
                    .weight(1f)
                    .fillMaxWidth()
                    .padding(horizontal = 16.dp),
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                // Header
                item {
                    val dateStr = DIGEST_DATE_FORMAT.format(Date(d.generatedAt))
                    Text(
                        text = dateStr,
                        style = MaterialTheme.typography.labelMedium,
                        color = MaterialTheme.colorScheme.onSurfaceVariant
                    )
                }

                // Recent Activity
                if (d.recentActivity.isNotEmpty()) {
                    item {
                        DigestSection(title = stringResource(R.string.daily_digest_section_recent)) {
                            d.recentActivity.forEach { item ->
                                DigestItem(
                                    title = item.noteTitle,
                                    subtitle = item.summary,
                                    trailing = {
                                        AssistChip(
                                            onClick = { onOpenNote(item.noteTitle) },
                                            label = {
                                                Text(
                                                    text = item.noteTitle.noteDisplayTitle(),
                                                    style = MaterialTheme.typography.labelSmall,
                                                    maxLines = 1,
                                                    overflow = TextOverflow.Ellipsis
                                                )
                                            },
                                            leadingIcon = {
                                                Icon(
                                                    Icons.Default.Description,
                                                    contentDescription = null,
                                                    modifier = Modifier.size(14.dp)
                                                )
                                            },
                                            modifier = Modifier.height(26.dp)
                                        )
                                    }
                                )
                            }
                        }
                    }
                }

                // Open Questions
                if (d.openQuestions.isNotEmpty()) {
                    item {
                        DigestSection(title = stringResource(R.string.daily_digest_section_questions)) {
                            d.openQuestions.forEach { item ->
                                DigestItem(
                                    title = item.concept,
                                    subtitle = item.detail,
                                    trailing = if (item.fromNote.isNotBlank() && item.fromNote != "unknown") {
                                        {
                                            AssistChip(
                                                onClick = { onOpenNote(item.fromNote) },
                                                label = {
                                                    Text(
                                                        text = item.fromNote.noteDisplayTitle(),
                                                        style = MaterialTheme.typography.labelSmall,
                                                        maxLines = 1,
                                                        overflow = TextOverflow.Ellipsis
                                                    )
                                                },
                                                leadingIcon = {
                                                    Icon(
                                                        Icons.Default.Description,
                                                        contentDescription = null,
                                                        modifier = Modifier.size(14.dp)
                                                    )
                                                },
                                                modifier = Modifier.height(26.dp)
                                            )
                                        }
                                    } else null
                                )
                            }
                        }
                    }
                }

                // Stale Concepts
                if (d.staleConcepts.isNotEmpty()) {
                    item {
                        DigestSection(title = stringResource(R.string.daily_digest_section_stale)) {
                            d.staleConcepts.forEach { item ->
                                DigestItem(
                                    title = item.concept,
                                    subtitle = stringResource(R.string.daily_digest_stale_days, item.daysSinceLastSeen),
                                    trailing = if (item.relatedNotes.isNotEmpty()) {
                                        {
                                            Row(horizontalArrangement = Arrangement.spacedBy(4.dp)) {
                                                item.relatedNotes.take(2).forEach { noteName ->
                                                    AssistChip(
                                                        onClick = { onOpenNote(noteName) },
                                                        label = {
                                                            Text(
                                                                text = noteName.noteDisplayTitle(),
                                                                style = MaterialTheme.typography.labelSmall,
                                                                maxLines = 1,
                                                                overflow = TextOverflow.Ellipsis
                                                            )
                                                        },
                                                        leadingIcon = {
                                                            Icon(
                                                                Icons.Default.Description,
                                                                contentDescription = null,
                                                                modifier = Modifier.size(14.dp)
                                                            )
                                                        },
                                                        modifier = Modifier.height(26.dp)
                                                    )
                                                }
                                            }
                                        }
                                    } else null
                                )
                            }
                        }
                    }
                }

                // Hidden Connections
                if (d.hiddenConnections.isNotEmpty()) {
                    item {
                        DigestSection(title = stringResource(R.string.daily_digest_section_connections)) {
                            d.hiddenConnections.forEach { item ->
                                DigestItem(
                                    title = "${item.conceptA} <-> ${item.conceptB}",
                                    subtitle = "${(item.strength * 100).toInt()}% overlap"
                                )
                            }
                        }
                    }
                }

                // Empty state when all sections are empty
                if (d.recentActivity.isEmpty() &&
                    d.openQuestions.isEmpty() &&
                    d.staleConcepts.isEmpty() &&
                    d.hiddenConnections.isEmpty()
                ) {
                    item {
                        Box(
                            modifier = Modifier
                                .fillMaxWidth()
                                .padding(vertical = 32.dp),
                            contentAlignment = Alignment.Center
                        ) {
                            Column(horizontalAlignment = Alignment.CenterHorizontally) {
                                Surface(
                                    shape = androidx.compose.foundation.shape.CircleShape,
                                    color = MaterialTheme.colorScheme.surfaceVariant,
                                    modifier = Modifier.size(48.dp)
                                ) {
                                    Box(contentAlignment = Alignment.Center, modifier = Modifier.fillMaxSize()) {
                                        Icon(
                                            Icons.Default.Summarize,
                                            contentDescription = null,
                                            tint = MaterialTheme.colorScheme.onSurfaceVariant,
                                            modifier = Modifier.size(24.dp)
                                        )
                                    }
                                }
                                Spacer(modifier = Modifier.height(12.dp))
                                Text(
                                    stringResource(R.string.daily_digest_nothing),
                                    style = MaterialTheme.typography.titleMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant
                                )
                                Spacer(modifier = Modifier.height(4.dp))
                                Text(
                                    stringResource(R.string.daily_digest_empty_hint),
                                    style = MaterialTheme.typography.bodyMedium,
                                    color = MaterialTheme.colorScheme.onSurfaceVariant
                                )
                            }
                        }
                    }
                }
            }
        }
        }
    }
}

@Composable
private fun DigestSection(
    title: String,
    content: @Composable ColumnScope.() -> Unit
) {
    Card(modifier = Modifier.fillMaxWidth()) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = title,
                style = MaterialTheme.typography.titleSmall,
                color = MaterialTheme.colorScheme.primary
            )
            Spacer(modifier = Modifier.height(8.dp))
            content()
        }
    }
}

@Composable
private fun DigestItem(
    title: String,
    subtitle: String,
    trailing: (@Composable () -> Unit)? = null
) {
    Column(modifier = Modifier.padding(vertical = 4.dp)) {
        Text(
            text = title,
            style = MaterialTheme.typography.bodyMedium,
            fontWeight = FontWeight.Medium
        )
        Text(
            text = subtitle,
            style = MaterialTheme.typography.bodySmall,
            color = MaterialTheme.colorScheme.onSurfaceVariant
        )
        if (trailing != null) {
            Spacer(modifier = Modifier.height(4.dp))
            trailing()
        }
    }
}
